site_name: Stock-Compass - Dcoumentação

nav:
  - Home: index.md
  - Documntação:
    - Metodologia: documentacao/metodologia.md
    - Políticas de Repositório: documentacao/politicas_de_repositorio.md
    - Lean Inception: documentacao/lean_inception.md
    - Documento de Visão: documentacao/documento_de_visao.md
    - Documento de Arquitetura: documentacao/documento_de_arquitetura.md
    - Identidade Visual: documentacao/identidade_visual.md
    - Protótipo: documentacao/prototipo.md
    - Qualidade do Produto: documentacao/qualidade_do_produto.md
    - Plano de Gerenciamento de Riscos: documentacao/plano_riscos.md
    - Backlog do Produto: documentacao/backlog_produto.md
  - Spints:
    - Backlog do Produto: sprints/sprint_1.md

